GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5d888114ad51dc51f08a2058

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscriberToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5d888114ad51dc51f08a2058

###

PATCH  http://localhost:3000/subscribers/5d8884628625c847c4bb7cd7
Content-Type: application/json

{
    "name": "New Subscriber"
}